# Site settings
name: "AI360Trading"
url: "https://ai360trading.in"
baseurl: ""
timezone: "Asia/Kolkata"
future: true

# SEO & Ownership (The ONLY place for these codes!)
# REPLACE the line below with your real code from Search Console
google_site_verification: YOUR_REAL_NEW_CODE
google_analytics: G-YR9E0CYRCV

# SEO & Permalinks
markdown: kramdown
highlighter: rouge
permalink: /:title/

# SOCIAL MEDIA
twitter_username: ai360trading
telegram_username: ai360trading

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
