# Dependencies
markdown:    kramdown
highlighter: rouge

# Permalinks
permalink:   none

# Setup
name:        "ai360trading"
url:         https://ai360trading.in
baseurl:     ""
logo:        /public/image/logo.webp
timezone:    Asia/Kolkata
future:      true        # IMPORTANT: Ensures your 2026 posts appear immediately

# Layout Settings
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      wide_layout: true   # Custom variable to trigger full-width CSS

author:
  name:      Amit Kumar
  email:     admin@ai360trading.in
  
facebook:
  publisher: ai360trading
  admin:     ai360trading
  username:  ai360trading

x:
  username:  ai360trading
instagram:
  username:  ai360trading
telegram:
  username:  ai360trading
youtube:
  username:  ai360trading

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

google_analytics: G-K9R4R0WD9C

tags: G-K9R4R0WD9C
