# Dependencies & Setup
markdown: kramdown
highlighter: rouge
encoding: "utf-8"
timezone: "Asia/Kolkata"
future: true

# Site Info
name: "AI360Trading"
url: "https://ai360trading.in"
baseurl: ""

# Permalinks (Clean URLs)
permalink: /:title/

# Default Layouts
defaults:
  - scope:
      path: ""
    values:
      layout: "default"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

exclude: [README.md, Gemfile, Gemfile.lock, node_modules, .sass-cache, .jekyll-cache, .git, vendor]
